
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Kunga
# Username: kchemi02
#
# Assignment: A03
# Purpose: To learn more about turtle
# Google Doc Link: https://docs.google.com/document/d/1HdsxhP0T-vBDLl6xvbjNdHFQC2ZNZ74Ksq5XVELKxSA/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle


def function_1():
    """
    Docstring for function_1
    """
    pass
    # ....


def function_2():
    """
    Docstring for function_2
    """
    pass
    # ...


def main():
    """
    Docstring for main
    """
    # ...
    function_1()            # Function call to function_1
    function_2()            # Function call to function_2


main()

