# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Daniela Ayala
# Username: danielaaya1a
#
# Assignment: A03 Functional Turtles 
# Purpose: 
# Continue practicing creating and using functions.
# More practice on using the turtle library.
# Learn about how computers represent colors.
# Learn about source control and git.
# Google Doc Link: https://docs.google.com/document/d/15JariKAoIbB3v93UVY5KAiMXwzenLD2fkWfubzqc55s/edit?usp=sharing 
#
#################################################################################
# Acknowledgements: Molly
#
#
#################################################################################

import turtle


def function_1(line):
    line.color("#5d5d5d")
    line.fillcolor("#919191")
    line.width(8)
    line.penup()
    line.setpos(-378, -320)
    line.pendown()
    line.begin_fill()
    for i in range(2):
        line.left(90)
        line.forward(360)
        line.right(90)
        line.forward(100)
        line.right(90)
        line.forward(400)
        line.left(90)
        for i in range(3):
            line.left(90)
            line.forward(450)
            line.right(90)
            line.forward(100)
            line.right(90)
            line.forward(470)
            line.left(90)

    # line.left(90)
    line.left(90)

    line.backward(190)
    line.left(90)
    line.forward(680)
    line.end_fill()


def function_2(line):
    line.shape("circle")
    line.width(3)
    line.color("blue")
    line.penup()
    line.setpos(-23, 45)
    line.pendown()
    line.right(90)
    line.forward(100)
    line.stamp()


def function_3(squ):
    squ.color("#a9fbfb")
    squ.width(3)
    # line.shape("circle")\
    squ.penup()
    squ.setpos(190, -30)
    squ.pendown()

    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(190, -50)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(190, -70)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(190, -90)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(160, -30)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(160, -50)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(160, -70)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)

    squ.penup()
    squ.setpos(160, -90)
    squ.pendown()
    for i in range(4):
        squ.right(90)
        squ.forward(10)


def function_4(box):
    box.begin_fill()
    box.width(3)
    box.penup()
    box.setpos(-220, 90)
    box.pendown()
    box.color("#5d5d5d")
    for i in range(2):
        box.left(90)
        box.forward(60)
        box.right(-90)
        box.forward(10)
    box.end_fill()


def function_5(bbox):
    bbox.begin_fill()
    bbox.width(3)
    bbox.penup()
    bbox.setpos(95, -60)
    bbox.pendown()
    bbox.color("#5d5d5d")
    for i in range(2):
        bbox.left(90)
        bbox.forward(20)
        bbox.right(-90)
        bbox.forward(40)
    bbox.end_fill()


def function_6(tri):
    tri.shape("triangle")
    tri.width(8)
    tri.color("#6201ab")
    tri.penup()
    tri.setpos(-325, 45)
    tri.pendown()
    tri.left(90)
    tri.forward(100)
    tri.stamp()


def function_7(mo):
    mo.width(3)
    mo.color("#656565")
    mo.penup()
    mo.setpos(300, 100)
    mo.color('orange')
    mo.begin_fill()
    mo.circle(100)
    mo.end_fill()
    mo.penup()
    mo.goto(350, 100)
    mo.pendown()
    mo.color("black")
    mo.begin_fill()
    mo.circle(100)
    mo.end_fill()


def main():
    wn = turtle.Screen()
    wn.bgcolor("black")
    line = turtle.Turtle()
    line.speed(10)
    squ = turtle.Turtle()
    box = turtle.Turtle()
    bbox = turtle.Turtle()
    tri = turtle.Turtle()
    mo = turtle.Turtle()

    function_1(line)
    function_2(line)
    function_3(squ)
    function_4(box)
    function_5(bbox)
    function_6(tri)
    function_7(mo)

    wn.exitonclick()


main()
