# Name: Jordan McVey
# Username: jordanmcvey
# Google Doc Link: https://docs.google.com/document/d/1nCyaghvpru-9iQ3ZZ1aq5c-jPhdi7VyoFElQ72eD3nk/edit?usp=sharing

import turtle
window = turtle.Screen()
window.bgcolor("aqua")
grass = turtle.Turtle()
tree = turtle.Turtle()
sun = turtle.Turtle()
grass.pensize(7)
grass.fillcolor("green")
grass.penup()
grass.right(90)
grass.forward(100)
grass.right(90)
grass.forward(380)
grass.left(180)
grass.color("green")
grass.pendown()
grass.begin_fill()
for i in range(2):
  grass.forward(755)
  grass.right(90)
  grass.forward(250)
  grass.right(90)
grass.end_fill()
grass.penup()
tree.color("brown")
tree.pensize(4)
tree.penup()
tree.right(90)
tree.forward(95)
tree.right(90)
tree.forward(250)
tree.left(90)
tree.forward(80)
tree.pendown()

def draw_tree(r,b):
  tree.pendown()
  tree.left(45)
  tree.forward(r)
  tree.penup()
  tree.backward(r)
  tree.pendown()
  tree.right(95)
  tree.forward(50)
  tree.penup()
  tree.backward(r)
  tree.right(130)
  tree.pendown()
  tree.forward(150)
  tree.penup()
  tree.backward(50)
  tree.pendown()
  tree.right(45)
  tree.forward(b)
  tree.penup()
  tree.backward(b)
  tree.left(90)
  tree.pendown()
  tree.forward(b)
  tree.penup()
  tree.backward(b)
  tree.pendown()
  tree.right(45)
  tree.forward(b+20)
  tree.penup()
  tree.backward(b+20)
  tree.pendown()
  tree.forward(100)
  tree.right(90)
  tree.forward(b)
  tree.backward(b)
  tree.left(90)
  tree.forward(b)
  tree.left(90)
  tree.pendown()
  tree.left(90)
  tree.forward(b+100)
  tree.left(135)
  tree.forward(b*2)
  tree.right(90)
  tree.forward(b)
  tree.backward(b)
  tree.left(90)
  tree.forward(b)
  tree.backward(b)
  tree.left(90)
  tree.forward(b)
  tree.backward(b)
  tree.left(90)
  tree.forward(b*2)
  tree.right(90)
  tree.forward(b*2)
  tree.right(90)
  tree.forward(b)
  tree.backward(b)
  tree.left(180)
  tree.forward(b)
  tree.backward(b)
  tree.right(90)
  tree.forward(b)
  tree.penup()



draw_tree(50,50)

tree.right(135)
tree.forward(300)
tree.right(90)
tree.forward(225)

draw_tree(50,50)

sun.color("yellow")
sun.pensize(5)
sun.penup()
sun.forward(270)
sun.left(90)
sun.forward(200)
sun.pendown()
sun.fillcolor("yellow")
sun.begin_fill()
sun.circle(50)
sun.end_fill()

window.exitonclick()