import turtle

wn = turtle.Screen()

def screen():
    wn.title("cute pokemon!")
    wn.bgcolor("skyblue")

def mat():
    face = turtle.Turtle()
    face.speed(10)
    face.hideturtle()
    face.penup()
    face.setpos(0,-100)
    face.pendown()
    face.color("orange")
    face.begin_fill()
    face.circle(180,360)
    face.end_fill()

def mieng():
    mouth = turtle.Turtle()
    mouth.speed(10)
    mouth.hideturtle()
    mouth.penup()
    mouth.setpos(-70,0)
    mouth.pendown()
    mouth.left(-45)
    mouth.color("yellow")
    mouth.begin_fill()
    for i in range(2):
        mouth.circle(100, 90)
        mouth.circle(100 // 2, 90)
    mouth.end_fill()

def nhan():
    eye1 = turtle.Turtle()
    eye2 = turtle.Turtle()
    eye3 = turtle.Turtle()
    eye4 = turtle.Turtle()
    eye1.speed(10)
    eye1.penup()
    eye1.setpos(-80, 100)
    eye1.pendown()
    eye1.color(101,67,33)
    eye1.begin_fill()
    eye1.circle(20, 360)
    eye1.end_fill()
    eye2.speed(10)
    eye2.penup()
    eye2.setpos(80, 100)
    eye2.pendown()
    eye2.color(101, 67, 33)
    eye2.begin_fill()
    eye2.circle(20, 360)
    eye2.end_fill()
    eye3.speed(10)
    eye3.hideturtle()
    eye3.penup()
    eye3.setpos(-90, 120)
    eye3.pendown()
    eye3.color(255,255,255)
    eye3.begin_fill()
    eye3.circle(5, 360)
    eye3.end_fill()
    eye4.speed(10)
    eye4.hideturtle()
    eye4.penup()
    eye4.setpos(70, 120)
    eye4.pendown()
    eye4.color("white")
    eye4.begin_fill()
    eye4.circle(5, 360)
    eye4.end_fill()

def than():
    body = turtle.Turtle()
    body2 = turtle.Turtle()
    body.speed(10)
    body.hideturtle()
    body.penup()
    body.setpos(90, -400)
    body.pendown()
    body.left(45)
    body.color(255, 165, 0)
    body.begin_fill()
    for i in range(2):
        body.circle(250, 90)
        body.circle(250 // 2, 90)
    body.end_fill()
    body2.speed(10)
    body2.hideturtle()
    body2.penup()
    body2.setpos(75, -400)
    body2.pendown()
    body2.left(45)
    body2.color(255, 200, 0)
    body2.begin_fill()
    for i in range(2):
        body2.circle(200, 90)
        body2.circle(200 // 2, 90)
    body2.end_fill()

def tay():
    tay1 = turtle.Turtle()
    tay2 = turtle.Turtle()
    tay1.speed(10)
    tay1.hideturtle()
    tay1.penup()
    tay1.setpos(-130, -50)
    tay1.pendown()
    tay1.left(-150)
    tay1.color(255, 205, 0)
    tay1.begin_fill()
    for i in range(2):
        tay1.circle(100, 90)
        tay1.circle(100 // 2, 90)
    tay1.end_fill()
    tay2.speed(10)
    tay2.hideturtle()
    tay2.penup()
    tay2.setpos(170, -170)
    tay2.pendown()
    tay2.left(70)
    tay2.color(255, 205, 0)
    tay2.begin_fill()
    for i in range(2):
        tay2.circle(100, 90)
        tay2.circle(100 // 2, 90)
    tay2.end_fill()

def main():
    turtle.colormode(255)
    screen()
    tay()
    than()
    mat()
    mieng()
    nhan()

main()

wn.exitonclick()